### ISSUE TITLE
Fix instructions

### ISSUE THREAD

**Issue by thawkin3** [mbloomfi/pixel-test#16]
The instructions are currently backwards, that if you are bigger than the other player, you get eaten, and if you're smaller, you eat them.

Could we also move the instructions above the input box, so that you see the title, how to play, and then you input your name and start playing? I think that's a more natural flow.

And then lastly, could we change up the actual content to the instructions? It's a little backwards to tell them to use the arrow keys to move their dot and then let them know that they are a dot. So maybe something like (everything centered like it currently is):

Instructions

You are a little colored dot and your only goal is to eat and survive. If you hit one of the bouncing red balls, you will be halved in size. If you hit someone who is smaller than you, then you eat them. If you hit someone larger, then you get eaten.

Use the arrow keys to move. 

Enjoy!

**Comment by mbloomfi** [comment]
Yes, this was a rush job so that I could test it with some of quni haha
