### ISSUE TITLE
Fix issue with eating a player locally but not emitting that to the other players

### ISSUE THREAD

**Issue by thawkin3** [mbloomfi/pixel-test#18]
There was that one bug we saw where I ate you on my screen but you survived on your screen, so you were essentially a ghost player that I couldn't see anymore even though you could still run around and eat food and stuff.

We talked about how maybe we should emit an event that the player had been eaten.

Does that still need resolving?

**Comment by mbloomfi** [comment]
Yeah - it happens occasionally, so it's worth resolving
