### ISSUE TITLE
Set up death handling

### ISSUE THREAD

**Issue by mbloomfi** [mbloomfi/pixel-test#3]
Will need some mongodb for scoring - 

Need routing/views for a high score and login page

Set up some type of scoring system - based on size & length of play as multiplier

**Comment by thawkin3** [comment]
The route exists right now to post a score, but I haven't written any code into the client-side game.js script to call that service on game end. The database is set up as well, it's called pixelsDB and the collection is called scores.

**Comment by thawkin3** [comment]
Now there's an AJAX request in the client-side game.js script that adds a score to the database. We still haven't worked out how to calculate the player's score, but when we do and have an event for the player to die, the route to post the score is working nicely.

**Comment by thawkin3** [comment]
Now the score is calculated as time * size

**Comment by thawkin3** [comment]
Tested on my server, and it works nicely with adding a score to the database.
