### ISSUE TITLE
Set up routing

### ISSUE THREAD

**Issue by mbloomfi** [mbloomfi/pixel-test#4]
Use actual routes rather than angular routes - allow page loads to break/stop JS functions for the game

**Comment by thawkin3** [comment]
Done! There are routes for:
"/" - game page
"/login" - login page
"/highscores" - high scores page

I haven't spent any time styling them up yet.

**Comment by thawkin3** [comment]
I've put in a little bit of styling for the views, so there's something there at least. I've also added two REST service routes to post a score and to get the top 10 high scores.
